// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOkMeA9twGGfnr4A-oIRToqLiIhmMSzg0',
    appId: '1:326329161668:web:dc99d89ef7156fee23f691',
    messagingSenderId: '326329161668',
    projectId: 'taxi-booking-app-389015',
    authDomain: 'taxi-booking-app-389015.firebaseapp.com',
    storageBucket: 'taxi-booking-app-389015.appspot.com',
    measurementId: 'G-SJQ73BNZVG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCajKdH7pFiWykA4RPyUalhhMP0eunEPVg',
    appId: '1:326329161668:android:440e44d4170d6ab223f691',
    messagingSenderId: '326329161668',
    projectId: 'taxi-booking-app-389015',
    storageBucket: 'taxi-booking-app-389015.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbcxWMw9pc7DkPetdY_523_WU_tMRlukA',
    appId: '1:326329161668:ios:273ae8ba0fcde38c23f691',
    messagingSenderId: '326329161668',
    projectId: 'taxi-booking-app-389015',
    storageBucket: 'taxi-booking-app-389015.appspot.com',
    androidClientId: '326329161668-ebs08r0tpnl1vv0kk82hnbk3ddvuhjjc.apps.googleusercontent.com',
    iosClientId: '326329161668-74hub634edqgk7cq306grj9pjt4i7f99.apps.googleusercontent.com',
    iosBundleId: 'com.example.taxiBookingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbcxWMw9pc7DkPetdY_523_WU_tMRlukA',
    appId: '1:326329161668:ios:273ae8ba0fcde38c23f691',
    messagingSenderId: '326329161668',
    projectId: 'taxi-booking-app-389015',
    storageBucket: 'taxi-booking-app-389015.appspot.com',
    androidClientId: '326329161668-ebs08r0tpnl1vv0kk82hnbk3ddvuhjjc.apps.googleusercontent.com',
    iosClientId: '326329161668-74hub634edqgk7cq306grj9pjt4i7f99.apps.googleusercontent.com',
    iosBundleId: 'com.example.taxiBookingApp',
  );
}
